# Setup
title:               Kwame Nkansah
tagline:             I build things.
description:         'Infra & Dev Wrangler.'
url:                 https://kwamenkansah.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kwame Nkansah
  url:               https://twitter.com/voltageek
  email:             voltageek@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
